import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Providers } from "~/components/providers";
import { Toaster } from "sonner";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "~/components/ui/sidebar";
import { AppSidebar } from "~/components/sidebar/app-sidebar";
import { Separator } from "~/components/ui/separator";
import { Breadcrumb, BreadcrumbList, BreadcrumbItem } from "~/components/ui/breadcrumb";
import BreadCrumbPageClient from "~/components/sidebar/breadcrumb-page-client";
import SoundBar from "~/components/sound-bar";

export const metadata: Metadata = {
  title: "XZ Music Generator",
  description: "Generated by Huggingface AI",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <Providers>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset className="flex h-screen flex-col">
                <header className="bg-background sticky-top z-10 border-b px-4 py-2">
                  <div className="flex shrink-0 grow items-center gap-2">
                    <SidebarTrigger className="-ml-1" />
                    <Separator orientation="vertical" className="mr-2 data-[orientation=vertical]:h-4" />
                    <Breadcrumb>
                      <BreadcrumbList>
                        <BreadcrumbItem>
                          <BreadCrumbPageClient />
                        </BreadcrumbItem>                        
                      </BreadcrumbList>
                    </Breadcrumb>
                  </div>
                </header>
                <main className="flex-1 overflow-y-auto">{children}</main>
                <SoundBar />
            </SidebarInset>
            
          </SidebarProvider>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
